environment:
  name: default

spring:
  application:
    name: SecureFileStorage
  security:
    user:
      password: abcd
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
    show-sql: true

# security config for JWT
security:
  jwt:
    secret-key: 5a108b6bb745866253bc6b253c366843688d2bc048454d9bf8115cbbb7105c88
    # token expiration time is 24 hours
    expiration-time: 86400000